betterBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import git_update_view
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
	path('', include('blog.urls')),
	path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('update_server/', git_update_view.update, name='production-update'),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
	
	path('toggleBookmark/', views.toggleBookmark, name='toggleBookmark'),
	path('blog-create/', views.BlogCreateView.as_view(), name='blog-create'),
	path('blog-update/<str:slug>/', views.BlogUpdateView.as_view(), name='blog-update'),
	path('deleteComment/<int:pk>/', views.DeleteComment.as_view(), name='deleteComment'),
	path('<str:slug>', views.BlogDetail.as_view(), name='blog-detail'),
	path('delete-blog/<str:slug>', views.BlogDeleteView.as_view(), name='blog-delete'),
	path('doAction/', views.action, name='action'),
	path('upload_image/', views.upload_image),


	path('', views.BlogList.as_view(), name='blog-list'),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.html import strip_tags
from django.core.exceptions import ValidationError
from django.template.defaultfilters import slugify
import random


User = get_user_model()

class Tag(models.Model):
	name = models.CharField(max_length=15)

	def __str__(self):
		return self.name


CHOICES = (
	(1, "Publish"),
	(0, "Draft")
)


class Blog(models.Model):
	title = models.CharField(max_length=20)
	author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	date_updated = models.DateTimeField(auto_now_add=True)
	content = models.TextField()
	tags = models.ManyToManyField(Tag)							# limiting number of tags to be max 5, admin can add more than 5 but users can't
	slug = models.CharField(max_length=30, unique=True)
	status = models.IntegerField(choices=CHOICES, default=0)
	img = models.ImageField(upload_to='posts', blank=True, null=True)
	n_views = models.IntegerField(default=0)

	def save(self, *args, **kwargs):
		if self._state.adding:
			slug = slugify(self.title)
			if Blog.objects.filter(slug=slug).exists():
				self.slug = slug+str(random.randrange(0, 10000))
			else:
				self.slug = slug
		super(Blog, self).save(*args, **kwargs)


	@property
	def read_time(self):
		plain_content = strip_tags(self.content)
		word_count = len(plain_content.split())   
		avg = 200

		minutes = word_count // avg
		seconds = (word_count/avg - minutes)*0.6

		if seconds > 0.3:
			minutes += 1

		if minutes == 0:
			minutes += 1

		return minutes


	def __str__(self):
		return self.title


class Bookmark(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)

	def __str__(self):
		return f'{self.user.username} - {self.blog}'


class Comment(models.Model):
	commenter = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	body = models.CharField(max_length=1000)
	blog = models.ForeignKey(Blog, models.CASCADE)
	date_created = models.DateTimeField(auto_now_add=True)
	parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.commenter.username} - {self.body}'

	class Meta:
		ordering = ['-date_created']

	def n_likes(self):
		return Opinion.objects.filter(action=1, comment=self).count()

	def n_dislikes(self):
		return Opinion.objects.filter(action=-1, comment=self).count()


OPINIONS = (
	(-1, 'dislike'),
	(0, 'neutral'),
	(1, 'like')
)
class Opinion(models.Model):
	user = models.ForeignKey(User, models.CASCADE)
	comment = models.ForeignKey(Comment, models.CASCADE)
	action = models.IntegerField(choices=OPINIONS, default=0)

	def __str__(self):
		return f'{self.user.username} - {self.comment.body} - {self.action}'

blog/forms.py
from django import forms
from .models import Comment, Blog
from django.http import HttpResponseRedirect


class CommentForm(forms.ModelForm):
	# reply_id = forms.CharField(max_length=100)
	class Meta:
		model = Comment
		fields = ['body']
		widgets = {
			'body': forms.TextInput(attrs={'placeholder': 'Add your Comment'})
		}


class BlogCreateForm(forms.ModelForm):
	test_category = forms.CharField(max_length=200)
	class Meta:
		model = Blog
		fields = ['title', 'content', 'status', 'img']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.urls import reverse

from .models import Blog, Tag, Comment, Bookmark, Opinion, Tag
from .forms import *
from django.http import Http404

from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.forms.models import model_to_dict

from datetime import datetime, timezone
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from django.conf import settings
from django.http import JsonResponse
import os


def my_login_required(function):
	def wrapper(request, *args, **kw):
		user=request.user  
		if not (user.id):
			return HttpResponse(json.dumps({'response': 'ERROR'}))
		else:
			return function(request, *args, **kw)
	return wrapper

class BlogCreateView(LoginRequiredMixin, CreateView):
	model = Blog
	template_name = 'blog/blog-form.html'
	form_class = BlogCreateForm
	success_url = '/accounts/my-blogs/'

	def form_valid(self, form):
		print(form.cleaned_data['test_category'], '*'*10)
		
		self.object = form.save(commit=False)
		self.object.author = self.request.user
		self.object.save()

		categories = form.cleaned_data['test_category']
		categories = categories.split()
		for category in categories:
			c, _ = Tag.objects.get_or_create(name=category)
			self.object.tags.add(c)	
		
		return HttpResponseRedirect(self.get_success_url())


class BlogUpdateView(LoginRequiredMixin, UpdateView):
	model = Blog
	template_name = 'blog/blog-update.html'
	form_class = BlogCreateForm
	success_url = '/accounts/my-blogs/'

	def get_object(self, queryset=None):
		obj = super(BlogUpdateView, self).get_object(queryset=queryset)
		if obj.author != self.request.user:
			raise Http404()
		return obj


class BlogDeleteView(LoginRequiredMixin, DeleteView):
	model = Blog
	success_url = '/accounts/my-blogs/'
	template_name = 'blog/blog_confirm_delete.html'

	def get_object(self, queryset=None):
		obj = super(BlogDeleteView, self).get_object(queryset=queryset)
		if obj.author != self.request.user:
			raise Http404()
		return obj


class BlogList(ListView):
	model = Blog
	template_name = 'blog/blog-list.html'
	context_object_name = 'blogs'
	paginate_by = 3
	queryset = Blog.objects.filter(status=1)


class BlogDetail(FormMixin, DetailView):
	model = Blog
	template_name = 'blog/blog-detail.html'
	slug_url_kwarg = 'slug'
	queryset = Blog.objects.filter(status=1)
	form_class = CommentForm

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		context['blog'].n_views += 1
		context['blog'].save()
		
		context['comment_form'] = CommentForm()
		context['bookmarked'] = True if self.request.user.is_authenticated and Bookmark.objects.filter(user=self.request.user, blog=context['blog']) else False
		context['comments'] = Comment.objects.filter(blog=context['blog'], parent=None)
		return context

	def post(self, *args, **kwargs):
		# form = self.get_context_data(**kwargs)['comment_form']
		form = CommentForm(self.request.POST)
		if form.is_valid():
			print("in form valid().")
			parent_obj = None
			try:
				parent_id = int(self.request.POST.get('parent_id'))
				print('parent_id = ', parent_id)
			except:
				parent_id = None
			if parent_id:
				parent_obj = Comment.objects.get(id=parent_id)

			commenter = self.request.user
			body = form.cleaned_data['body']
			blog = self.get_object()

			if parent_obj:
				Comment(commenter=commenter, body=body, blog=blog, parent=parent_obj).save()
			else:
				Comment(commenter=commenter, body=body, blog=blog).save()
			return HttpResponseRedirect(reverse('blog-detail', kwargs={'slug': self.get_object().slug}))


class DeleteComment(LoginRequiredMixin, DeleteView):
	model = Comment

	def get(self, *args, **kwargs):
		return self.post(*args, **kwargs)

	def get_success_url(self):
		print('*'*30)
		return reverse('blog-detail', kwargs={"slug": self.get_object().blog.slug})



@csrf_exempt
@my_login_required
def toggleBookmark(request):
	data = json.loads(request.body)
	try:
		slug = data['slug']
		blog = get_object_or_404(Blog, slug=slug)

		if Bookmark.objects.filter(user=request.user, blog=blog) .exists():
			print('it exists. and now deleting.')
			Bookmark.objects.get(user=request.user, blog=blog).delete()
			status = False

		else:
			print("Does not exist creating now.")
			bookmark = Bookmark.objects.create(user=request.user, blog=blog)
			bookmark.save()
			status = True

		response = json.dumps({'response': 'OK', 'status': status})

	except Exception as e:
		response = json.dumps({'response': 'ERROR'})

	return HttpResponse(response)


@login_required
@csrf_exempt
def action(request):
	data = json.loads(request.body)
	try:
		commentId = data['commentId']
		action = data['action']
		print(commentId, action)

		comment = get_object_or_404(Comment, id=commentId)

		op, _ = Opinion.objects.get_or_create(user=request.user, comment=comment)

		if action == "LIKE": status = 1
		if action == "DISLIKE": status = -1

		if status == op.action:
			op.delete()
			status = 0
		else: 
			op.action = status
			op.save()

		response = json.dumps({'response': 'OK', 'like': status==1, 'dislike': status==-1, 'nlikes': comment.n_likes()})

	except:
		response = json.dumps({'response': 'ERROR'})

	return HttpResponse(response)


@login_required
@csrf_exempt
def upload_image(request):
	if request.method == "POST":
		file_obj = request.FILES['file']
		file_name_suffix = file_obj.name.split(".")[-1]
		if file_name_suffix not in ["jpg", "png", "gif", "jpeg", ]:
			return JsonResponse({"message": "Wrong file format"})

		path = os.path.join(
			settings.MEDIA_ROOT,
			'tinymce',
		)
		# If there is no such path, create
		if not os.path.exists(path):
			os.makedirs(path)

		file_path = os.path.join(path, file_obj.name)

		file_url = f'{settings.MEDIA_URL}tinymce/{file_obj.name}'

		if os.path.exists(file_path):
			return JsonResponse({
				"message": "file already exist",
				'location': file_url
			})

		with open(file_path, 'wb+') as f:
			for chunk in file_obj.chunks():
				f.write(chunk)

		return JsonResponse({
			'message': 'Image uploaded successfully',
			'location': file_url
		})
	return JsonResponse({'detail': "Wrong request"})

blog/templates/blog/blog-form.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}


{% block main %}

{% include 'header.html' %}

<main>
			<section class="section-header pb-5 pb-sm-7 bg-primary text-white">
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-12 col-lg-10 text-center">
							<h1 class="display-3 mb-4 px-lg-5">Create Blog</h1>
						</div>
					</div>
				</div>
			</section>

<div class="section section-md pt-4">
	<div class="container">
		<div class="row mb-4 mb-lg-5">
			
				<div class="col-lg-12 col-sm-12">

				{% if form.errors %}
					{% for field in form %}
						{% for error in field.errors %}
								<div class="alert alert-danger" role="alert">
								<strong>{{ field.name | title }} - {{ error|escape }}</strong>
							</div>
						{% endfor %}
					{% endfor %}
					{% for error in form.non_field_errors %}
								<div class="alert alert-danger" role="alert">
							<strong>{{ error|escape }}</strong>
						</div>
					{% endfor %}				
				{% endif %}

				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="mb-4">
						<label for="id_title">Blog title</label>
						<input class="form-control" name="{{ form.title.name }}" id="id_title">
					</div>

					<div class="mb-4">
						<label for="id_title">Categories</label>
						<input class="form-control" name="test_category">
						<small id="emailHelp" class="form-text text-gray">Categories seprated by a space. Max 5 categories allowed</small>
					</div>

					<div class="mb-4">
						<label for="id_content">Content</label>
						<textarea type="text" class="form-control" name="{{ form.content.name }}" id="id_content"></textarea>
					</div>

					<div class="mb-4">
						<label for="id_status">Status</label><br>
						<select name="status" id="id_status" class="form-select" id="inlineFormCustomSelectPref" aria-label="Default select example">
						  <option selected="">----------</option>
						  <option value="0">Draft</option>
						  <option value="1">Publish</option>
						</select>
					</div>

					<div class="mb-4">
						<label for="id_img">Blog image</label>
						<input class="form-control" type="file" id="id_img" name="img">
						<small id="emailHelp" class="form-text text-gray">It's like a display image of your blog. Choose Wisely.</small>
					</div>

				<button class="btn btn-primary" type="submit">Button</button>			
				</form>
			</div>
		
		</div>
	</div>
</div>
</main>


<script src="{% static 'tinyInject.js' %}"></script>


{% include 'footer.html' %}
{% endblock %}

blog/templates/blog/blog-list.html
{% extends 'base.html' %}
{% load static  %}


{% block main %}
{% include 'header.html' %}

		<main>
			<div class="preloader bg-dark flex-column justify-content-center align-items-center">
				<svg id="loader-logo" xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 64 78.4">
					<path fill="#fff" d="M10,0h1.2V11.2H0V10A10,10,0,0,1,10,0Z"/>
					<rect fill="none" stroke="#fff" stroke-width="11.2" x="40" y="17.6" width="0" height="25.6"/>
					<rect fill="none" stroke="#fff" stroke-opacity="0.4" stroke-width="11.2" x="23" y="35.2" width="0" height="25.6"/>
					<path fill="#fff" d="M52.8,35.2H64V53.8a7,7,0,0,1-7,7H52.8V35.2Z"/>
					<rect fill="none" stroke="#fff" stroke-width="11.2" x="6" y="52.8" width="0" height="25.6"/>
					<path fill="#fff" d="M52.8,0H57a7,7,0,0,1,7,7h0v4.2H52.8V0Z"/>
					<rect fill="none" stroke="#fff" stroke-opacity="0.4" stroke-width="11.2" x="57.8" y="17.6" width="0" height="11.2"/>
					<rect fill="none" stroke="#fff" stroke-width="11.2" x="6" y="35.2" width="0" height="11.2"/>
					<rect fill="none" stroke="#fff" stroke-width="11.2" x="40.2" y="49.6" width="0" height="11.2"/>
					<path fill="#fff" d="M17.6,67.2H28.8v1.2a10,10,0,0,1-10,10H17.6V67.2Z"/>
					<rect fill="none" stroke="#fff" stroke-opacity="0.4" stroke-width="28.8" x="31.6" width="0" height="11.2"/>
					<rect fill="none" stroke="#fff" x="14" stroke-width="28.8" y="17.6" width="0" height="11.2"/>
				</svg>
			</div>
			<section class="section-header bg-primary text-white pb-10 pb-sm-8 pb-lg-11">
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-12 col-md-8 text-center">
							<h1 class="display-2 mb-4">Better Blog</h1>
							<p class="lead">A blog app created using django CBVs.</p>
						</div>
					</div>
				</div>
			</section>
			<section class="section section-lg line-bottom-light">
				<div class="container mt-n10 mt-lg-n12 z-2">
					<div class="row">

						<!-- featured post -->
<!--                         <div class="col-lg-12 mb-5">
							<div class="card shadow bg-white border-gray-300 flex-lg-row align-items-center g-0 p-4">
								<a href="./blog-post.html" class="col-12 col-lg-6">
									<img src="../../assets/img/blog/image-1.jpg" alt="themesberg office" class="card-img-top rounded">
								</a>
								<div class="card-body d-flex flex-column justify-content-between col-auto py-4 p-0 p-lg-3 p-xl-5">
									<a href="./blog-post.html">
										<h2>Designing a dashboard that increases business value</h2>
									</a>
									<p>Today we are overwhelmed by content, and inspiration can strike anywhere. The point is to collect it and share it in a structured way to inspire your team, client, and users. In this article, I will show you how to design a dashboard.</p>
									<div class="d-flex align-items-center mt-3">
										<img class="avatar avatar-sm rounded-circle" src="../../assets/img/team/profile-picture-1.jpg" alt="Richard avatar">
										<h3 class="h6 small ms-2 mb-0">Richard Thomas</h3>
										<span class="h6 text-muted small fw-normal mb-0 ms-auto">
											<time datetime="2019-04-25">21 February, 2019</time>
										</span>
									</div>
								</div>
							</div>
						</div> -->

						<!-- normal posts -->
						{% for blog in blogs %}
							<div class="col-12 col-md-6 col-lg-4 mb-4 mb-lg-5">
								<div class="card shadow bg-white border-gray-300 p-4 rounded">
									<a href="{% url 'blog-detail' blog.slug %}">
										<img src="{{ blog.img.url }}" class="card-img-top rounded" alt="blog.title">
									</a>
									<div class="card-body p-0 pt-4">
										<a href="{% url 'blog-detail' blog.slug %}" class="h4">{{ blog.title }}</a>
										<div class="d-flex align-items-center my-3">
											<img class="avatar avatar-sm rounded-circle" src="{{ blog.author.profile.img.url }}" alt="{{ blog.author.username }}">
											<h3 class="h6 small ms-2 mb-0">
												{{  blog.author.profile.first_name|default:blog.author.username }}
											</h3>
										</div>
										<p class="mb-0">{{ blog.content | striptags | truncatewords:35 }}</p>
									</div>
								</div>
							</div>
						{% endfor %}

						<div class="col-12">
							<div class="d-flex justify-content-center">
								<nav aria-label="Page navigation example">
									<ul class="pagination">

										<br>

										{% if page_obj.has_previous %}
											<li class="page-item">
												<a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a>
											</li>

											<li class="page-item">
												<a class="page-link" href="?page={{page_obj.previous_page_number}}">{{page_obj.previous_page_number}}</a>
											</li>
										{% endif %}

										<li class="page-item active">
											<a class="page-link" href="#">{{page_obj.number}}</a>
										</li>

										{% if page_obj.has_next %}
											<li class="page-item">
												<a class="page-link" href="?page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}</a>
											</li>
											<li class="page-item">
												<a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
											</li>
										{% endif %}

									</ul>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</section>
		</main>

{% include 'footer.html' %}
{% endblock %}

blog/templates/blog/blog-update.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}


{% block main %}

{% include 'header.html' %}

<main>
			<section class="section-header pb-5 pb-sm-7 bg-primary text-white">
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-12 col-lg-10 text-center">
							<h1 class="display-3 mb-4 px-lg-5">Create Blog</h1>
						</div>
					</div>
				</div>
			</section>

<div class="section section-md pt-4">
	<div class="container">
		<div class="row mb-4 mb-lg-5">
			
				<div class="col-lg-12 col-sm-12">

				{% if form.errors %}
					{% for field in form %}
						{% for error in field.errors %}
								<div class="alert alert-danger" role="alert">
								<strong>{{ field.name | title }} - {{ error|escape }}</strong>
							</div>
						{% endfor %}
					{% endfor %}
					{% for error in form.non_field_errors %}
								<div class="alert alert-danger" role="alert">
							<strong>{{ error|escape }}</strong>
						</div>
					{% endfor %}				
				{% endif %}


				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="mb-4">
						<label for="id_title">Blog title</label>
						<input class="form-control" name="{{ form.title.name }}" id="id_title" value="{{ form.title.value }}">
					</div>

					<div class="mb-4">
						<label for="id_title">Categories</label>
						<input class="form-control" name="test_category" value="{% for c in blog.tags.all %} {{ c }} {% endfor %}">
						<small id="emailHelp" class="form-text text-gray">Categories seprated by a space. Max 5 categories allowed</small>
					</div>

					<div class="mb-4">
						<label for="id_content">Content</label>
						<textarea type="text" class="form-control" name="{{ form.content.name }}" id="id_content"> {{ form.content.value }} </textarea>
					</div>

					<div class="mb-4">
						<label for="id_status">Status</label><br>
						<select name="status" id="id_status" class="form-select" id="inlineFormCustomSelectPref" aria-label="Default select example">
						  <option value="0" {% if form.status.value == 0 %} selected {% endif %}>Draft</option>
						  <option value="1" {% if form.status.value == 1 %} selected {% endif %}>Publish</option>
						</select>
					</div>

					<div class="mb-4">
						<label for="id_img">Blog image</label><br>Currently: <a href="{{ blog.img.url }}" target="_blank">{{ blog.img }}</a> 
						<input class="form-control" type="file" id="id_img" name="img">
						<small id="emailHelp" class="form-text text-gray">It's like a display image of your blog. Choose Wisely.</small>
					</div>

				<button class="btn btn-primary" type="submit">Update</button>			
				</form>
			</div>
		
		</div>
	</div>
</div>
</main>


<script src="{% static 'tinyInject.js' %}"></script>


{% include 'footer.html' %}
{% endblock %}

blog/templates/blog/blog_confirm_delete.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

<main>
  <section class="min-vh-100 d-flex align-items-center section-image overlay-soft-dark" data-background="{% static 'img/pages/form-image.jpg' %}">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12">
          <div class="text-center text-md-center mb-3 mt-md-0 text-white">
            <h1 class="mb-0 h3">Delete Blog</h1>
          </div>
        </div>
        <div class="col-12 d-flex align-items-center justify-content-center">
          <div class="signin-inner my-4 my-lg-0 bg-white shadow-soft border rounded border-gray-300 p-4 p-lg-5 w-100 fmxw-500">
            <form method="POST">
            	{% csrf_token %}
              <div class="form-group mb-4">
                <label for="email">Are you sure want to delete {{ object }}. Once deleted, cannot be recovered at any cost.</label>
              </div>
              <div class="d-grid">
                <button type="submit" class="btn btn-primary">Delete</button>
              </div>
            </form>
            <div class="d-flex justify-content-center align-items-center mt-4">
              <span class="fw-normal">Back to <a href="{% url 'my-blogs' %}" class="fw-bold text-underline">my blogs</a>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

{% endblock %}